### ISSUE TITLE
[Suggestion] Is it possible to make setlocal completefunc=xolox#lua#completefunc is an optiona

### ISSUE THREAD

**Issue by guotsuan** [xolox/vim-lua-ftplugin#15]
Hi,

I notice in the ftplugin/lua.vim the completefunc was set. I'm wondering if it is possbile make it as an option, like:
if g:lua_set_completefunc
    setlocal completefunc= xolox#lua#completefunc
endif

The reason I suggested is some auto complete plugins for exmaple neocomplete like to occopy the completefunc setting. Such auto complete plugins will collect all kinds of candiates from differet sources including the xolox#lua#completefunc. 

The option if g:lua_set_completefunc could make these auto complete plugins happy and the  xolox#lua#completefunc will still be functional by  feeding the complete  candidates to these auto complete plugins.

Thank you for the consideration.

Best regards,

Quan

**Comment by xolox** [comment]
As you suggested I just added an option ([lua_define_completefunc](http://peterodding.com/code/vim/lua-ftplugin#lua_define_completefunc_option)) so that the setting of 'completefunc' can be disabled. I also added a similar option to disable the setting of 'omnifunc'. I'm closing this issue but if you have any further feedback feel free to reopen this issue or create a new one. Happy Vimming!
