### ISSUE TITLE
error running :helptags

### ISSUE THREAD

**Issue by kevwil** [xolox/vim-lua-ftplugin#9]
I have this plugin installed using Vundle, and when I install or update it, I get:

`Error running :helptags /Users/willkd9/.vim/bundle/vim-lua-ftplugin/doc/`

I don't see any other useful output, so I'm not sure what more I can do to help troubleshoot this error. Is anyone else seeing the same error with helptags?

**Comment by xolox** [comment]
With some luck the latest version of the plug-in should no longer cause this problem (a problem with the help file was fixed in 46466bb12e559ea4b6191761079dea4031414a5e); please try the latest version. If the problem persists, feel free to reopen this issue, but in that case I'll need more detailed error messages or a way to reproduce them.

**Comment by Atcold** [comment]
This error is still there.
